# action.yml
name: 'Register Workflow with Prefect Cloud'
inputs:
  workflow-path:
    description: 'Workflow Path'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workflow-path }}