# action.yml
name: 'Prefect Register'
description: 'Register workflows with Prefect Cloud'
inputs:
  workflow_repository_path:
    description: 'Path where the workflow lives'
    required: true
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}